<a href="https://colab.research.google.com/github/Utkarshmishra2k2/Wield-Of-Numpy/blob/main/Numpy%20Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing NumPy

In [ ]:
import numpy as np

In [ ]:
N=100000000

In [ ]:
%%time
Arr=np.arange(N)
Arr=Arr*Arr

CPU times: user 245 ms, sys: 573 ms, total: 819 ms
Wall time: 892 ms


In [ ]:
%%time
Arr=np.arange(N)
Arr_S=np.sum(Arr)

CPU times: user 199 ms, sys: 5.11 ms, total: 204 ms
Wall time: 202 ms


Array

In [ ]:
Array=np.arange(14)
print(Array,type(Array),id(Array))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] <class 'numpy.ndarray'> 140540091915216


In [ ]:
Array01=np.array([14,12,1,3])               
print(Array01,type(Array01),id(Array01))    

[14 12  1  3] <class 'numpy.ndarray'> 140540091915696


In [ ]:
Array01.dtype      

dtype('int64')

In [ ]:
Array01.ndim        

1

In [ ]:
Array01.shape 

(4,)

In [ ]:
Array01.size    

4

In [ ]:
Array01.itemsize   

8

In [ ]:
Array02=np.array([
                 [14,28,42,56],
                 [70,84,98,112],
                 [126,140,154,168] 
])   

In [ ]:
Array02,Array02.ndim,Array02.size,Array02.shape,Array02.itemsize,Array02,id

(array([[ 14,  28,  42,  56],
        [ 70,  84,  98, 112],
        [126, 140, 154, 168]]), 2, 12, (3, 4), 8, array([[ 14,  28,  42,  56],
        [ 70,  84,  98, 112],
        [126, 140, 154, 168]]), <function id(obj, /)>)

In [ ]:
Array02.ndim

2

In [ ]:
Array03=np.array([
                  [
                   [1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13]
                  ],
                  [
                   [15,16,17,18,19],
                   [20,21,22,23,24],
                   [25,26,27,28,29]
                  ]
])     

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [ ]:
Array03,Array03.ndim,Array03.size,Array03.shape,Array03.itemsize 

(array([[list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
         list([11, 12, 13])],
        [list([15, 16, 17, 18, 19]), list([20, 21, 22, 23, 24]),
         list([25, 26, 27, 28, 29])]], dtype=object), 2, 6, (2, 3), 8)

In [ ]:
np.ones((5,10,15,16,17,18))  

array([[[[[[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          ...,

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1.,

In [ ]:
14122002*np.ones((5,10,15,16,17,18))  

array([[[[[[14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           ...,
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.]],

          [[14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
           ...,
           [14122002., 14122002., 14122002., ..., 14122002.,
            14122002., 14122002.],
      

In [ ]:
np.zeros((5,10,15,16,17,18))   

array([[[[[[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          ...,

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0.,

In [ ]:
np.random.randn(14,12)    

array([[-0.33977797, -0.03540798, -0.35451818,  0.58972736, -0.15149285,
        -0.33325952,  0.48315998, -1.62466354,  1.13902914,  1.08134071,
         0.53466257,  0.58762393],
       [-1.47387041,  0.61509085, -1.56712494, -0.47969861, -0.02170358,
         0.58405424, -0.07559497,  2.35850753, -0.64912859,  0.29635567,
         0.15479694,  0.24321326],
       [-0.2600943 ,  0.34423788,  0.78593049, -1.61353959,  0.83099127,
        -1.32055137, -1.18177812, -1.71230894,  1.3930144 , -0.17741086,
        -0.10538915, -1.5518618 ],
       [ 0.44976781,  0.24482029,  0.86626095, -1.72725907, -0.43751146,
        -0.01093048,  1.04088341, -0.31139347,  0.3733442 ,  0.54030739,
        -2.39641036,  0.23876581],
       [ 0.43444098, -0.14855603,  1.89601905,  0.67899023, -0.81400797,
         1.26508416, -1.10484258,  0.75555556, -0.40034327,  1.41424384,
        -0.87301982, -1.18599847],
       [-0.10899292, -0.03222338,  0.01136932, -1.52859089,  1.76008657,
        -1.35247133,  

In [ ]:
np.random.rand(14,12)   

array([[0.53857815, 0.49872203, 0.49770931, 0.35115095, 0.63669722,
        0.62203725, 0.93967718, 0.34986692, 0.70662341, 0.01715008,
        0.90605379, 0.47956662],
       [0.56424597, 0.32401085, 0.87044902, 0.735074  , 0.58754467,
        0.8986882 , 0.6845153 , 0.11311729, 0.82317869, 0.35210861,
        0.01457675, 0.83904624],
       [0.85694021, 0.119796  , 0.35781779, 0.23321323, 0.05303707,
        0.63755613, 0.27586077, 0.9555852 , 0.29978629, 0.77431527,
        0.82548113, 0.24466966],
       [0.5178386 , 0.92199353, 0.96104805, 0.63829276, 0.37098403,
        0.1651525 , 0.06007776, 0.50136489, 0.73337973, 0.75689155,
        0.521997  , 0.09743288],
       [0.39762797, 0.66259033, 0.64994857, 0.35265922, 0.16318362,
        0.05744899, 0.46596437, 0.7880377 , 0.14052843, 0.46707307,
        0.20064531, 0.4947342 ],
       [0.22335929, 0.04804525, 0.74421667, 0.76307982, 0.74390495,
        0.20740864, 0.94558459, 0.12805467, 0.48157795, 0.35044827,
        0.92915188,

In [ ]:
np.random.randint(14,14122002,(14,12))     

array([[ 7896919,  6053334,  7207550,  9906646,   259994,  8786100,
        13142996,  5395559,  9908453,  9148305,  8712992, 12547895],
       [10789136,  5021459, 12833921,  5768636,  2931064,  8078906,
         3424221,  1334057,  1375820,  5243299, 10405889,  5809755],
       [  104332, 10769051,  8540102, 13616304, 13508881,  6339212,
         5459927,  9897943,  1087516,  2588428, 11559271,  3962933],
       [13241650,  5376366,  7624784, 12956468,  9532583,  4673391,
        11988672, 10119947,  1403084, 10500590,  7033634,   528721],
       [13528770, 12947311,  1113239,  3763559,   211101,  4500005,
         1636857,  5870730,   940187,  8752057,  7024961,  2350489],
       [ 5112728, 12195146,  3616042,  4300301,  6143608, 13319541,
         2100487,  1206887,  1266278, 11799454, 12005588, 10849696],
       [ 6168200,  4917538,  3822578,  4019963,  1298416,  4403467,
         4823672,  2402617,  7967106,  4302223,  7429470,   841629],
       [ 7458262, 13767195,  3749486,  27

In [ ]:
np.arange(14,1412,3)  

array([  14,   17,   20,   23,   26,   29,   32,   35,   38,   41,   44,
         47,   50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
         80,   83,   86,   89,   92,   95,   98,  101,  104,  107,  110,
        113,  116,  119,  122,  125,  128,  131,  134,  137,  140,  143,
        146,  149,  152,  155,  158,  161,  164,  167,  170,  173,  176,
        179,  182,  185,  188,  191,  194,  197,  200,  203,  206,  209,
        212,  215,  218,  221,  224,  227,  230,  233,  236,  239,  242,
        245,  248,  251,  254,  257,  260,  263,  266,  269,  272,  275,
        278,  281,  284,  287,  290,  293,  296,  299,  302,  305,  308,
        311,  314,  317,  320,  323,  326,  329,  332,  335,  338,  341,
        344,  347,  350,  353,  356,  359,  362,  365,  368,  371,  374,
        377,  380,  383,  386,  389,  392,  395,  398,  401,  404,  407,
        410,  413,  416,  419,  422,  425,  428,  431,  434,  437,  440,
        443,  446,  449,  452,  455,  458,  461,  4

In [ ]:
np.linspace(14,24,5) 

array([14. , 16.5, 19. , 21.5, 24. ])

In [ ]:
Array04=np.array(Array,dtype='float')   
Array04

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13.])

###Indexing of Array

In [ ]:
Array03=np.array([
                  [
                   [1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13]
                  ],
                  [
                   [15,16,17,18,19],
                   [20,21,22,23,24],
                   [25,26,27,28,29]
                  ]
])   

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [ ]:
Array03[1][0][3]  

18

In [ ]:
Array03[0]        

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]), list([11, 12, 13])],
      dtype=object)

In [ ]:
Array03[:][0]

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]), list([11, 12, 13])],
      dtype=object)

In [ ]:
Array03[:][:][0:1]

array([[list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
        list([11, 12, 13])]], dtype=object)

In [ ]:
Array02 % 2==0     

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
Array02[Array02 % 2==0] 

array([ 14,  28,  42,  56,  70,  84,  98, 112, 126, 140, 154, 168])

In [ ]:
Array05=np.arange(55)  
Array05

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [ ]:
Array05[(Array05 % 2==1) & (Array05 * 2==18)]

array([9])

In [ ]:
Array05[2:6]   

array([2, 3, 4, 5])

In [ ]:
Array05[54]=55  
Array05

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 55])

In [ ]:
ArrayIndecis01=[1,9,25,32,49]  
Array05[ArrayIndecis01]         

array([ 1,  9, 25, 32, 49])

Operations On Array

In [ ]:
Array06=np.random.randint(0,25,(2,5,6))   

In [ ]:
Array07=np.random.randint(0,65,(2,5,6))   
Array07

array([[[33,  3, 15, 20, 36, 48],
        [13,  5, 45, 60, 39, 13],
        [19, 12, 44, 53, 51, 50],
        [12, 45, 19, 48, 14, 19],
        [52, 15, 29, 34, 24, 21]],

       [[15, 34, 56, 42, 35, 56],
        [29, 34, 26, 32, 55, 42],
        [ 1, 61, 17,  8, 53, 11],
        [27, 26, 44, 25, 20,  4],
        [36, 34, 25, 25, 59,  4]]])

In [ ]:
Array06+Array07   

array([[[36, 16, 26, 27, 60, 64],
        [18, 15, 64, 77, 39, 13],
        [42, 22, 53, 66, 73, 65],
        [25, 50, 27, 51, 20, 43],
        [60, 22, 33, 50, 30, 42]],

       [[25, 38, 73, 52, 44, 58],
        [49, 50, 32, 38, 63, 60],
        [24, 61, 19, 17, 53, 33],
        [39, 41, 56, 32, 34, 14],
        [48, 43, 49, 36, 83, 22]]])

In [ ]:
Array06*Array07   

array([[[  99,   39,  165,  140,  864,  768],
        [  65,   50,  855, 1020,    0,    0],
        [ 437,  120,  396,  689, 1122,  750],
        [ 156,  225,  152,  144,   84,  456],
        [ 416,  105,  116,  544,  144,  441]],

       [[ 150,  136,  952,  420,  315,  112],
        [ 580,  544,  156,  192,  440,  756],
        [  23,    0,   34,   72,    0,  242],
        [ 324,  390,  528,  175,  280,   40],
        [ 432,  306,  600,  275, 1416,   72]]])

In [ ]:
np.exp2(Array06)*np.exp2(Array07)  

array([[[6.87194767e+10, 6.55360000e+04, 6.71088640e+07, 1.34217728e+08,
         1.15292150e+18, 1.84467441e+19],
        [2.62144000e+05, 3.27680000e+04, 1.84467441e+19, 1.51115727e+23,
         5.49755814e+11, 8.19200000e+03],
        [4.39804651e+12, 4.19430400e+06, 9.00719925e+15, 7.37869763e+19,
         9.44473297e+21, 3.68934881e+19],
        [3.35544320e+07, 1.12589991e+15, 1.34217728e+08, 2.25179981e+15,
         1.04857600e+06, 8.79609302e+12],
        [1.15292150e+18, 4.19430400e+06, 8.58993459e+09, 1.12589991e+15,
         1.07374182e+09, 4.39804651e+12]],

       [[3.35544320e+07, 2.74877907e+11, 9.44473297e+21, 4.50359963e+15,
         1.75921860e+13, 2.88230376e+17],
        [5.62949953e+14, 1.12589991e+15, 4.29496730e+09, 2.74877907e+11,
         9.22337204e+18, 1.15292150e+18],
        [1.67772160e+07, 2.30584301e+18, 5.24288000e+05, 1.31072000e+05,
         9.00719925e+15, 8.58993459e+09],
        [5.49755814e+11, 2.19902326e+12, 7.20575940e+16, 4.29496730e+09,
     

In [ ]:
#Here All Mathematical Calcution Are Applied 

In [ ]:
Array08=np.zeros((2,2,2))   
Array08

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
ArrayTest=1/Array08
ArrayTest

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf]]])

In [ ]:
np.isinf(ArrayTest[1][1][1])  

True

In [ ]:
np.isinf(ArrayTest)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

Exercise:-
Finding The Number Of Points Outside The N-Dimensional Spheres 

In [ ]:
NoDim=2       
NoPoints=1000000  

In [ ]:
Points=np.random.rand(NoPoints,NoDim)     
Points

array([[0.24283682, 0.38566721],
       [0.19970905, 0.33403349],
       [0.84003913, 0.4646786 ],
       ...,
       [0.77868397, 0.86764361],
       [0.83048859, 0.61267556],
       [0.86647055, 0.68016477]])

In [ ]:
DistanceFromOrigin=np.zeros((NoPoints,1))
OutsidePoints = 0

In [ ]:
%%time
for U in range(NoPoints):
    for T in range(NoDim):
        DistanceFromOrigin[U]+=Points[U,T]**2
    DistanceFromOrigin[U]=np.sqrt(DistanceFromOrigin[U])
    if DistanceFromOrigin[U]>1:
        OutsidePoints+=1

CPU times: user 16.6 s, sys: 2.04 s, total: 18.6 s
Wall time: 17.9 s


In [ ]:
print("Fraction of Points Outside Is ",OutsidePoints/NoPoints)

Fraction of Points Outside Is  0.215037


In [ ]:
#Now i Will Do The Proble Using Numpy Functions

In [ ]:
%%time
SquarePoints = Points*Points
DistanceFromOrigin=np.sqrt(np.sum(SquarePoints,axis=1))   
OutsidePoints= np.sum(DistanceFromOrigin>1)

CPU times: user 35.8 ms, sys: 0 ns, total: 35.8 ms
Wall time: 39.1 ms


In [ ]:
print("Fraction of Points Outside Is ",OutsidePoints/NoPoints)

Fraction of Points Outside Is  0.215037


Broadcasting

In [ ]:
Array09=np.arange(55)
Array09,Array09.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54]), (55,))

In [ ]:
Array09=Array09.reshape((11,5))
Array09

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

File Handling Using NumPy

In [ ]:
import numpy as np

In [ ]:
#Here I Dont Have Proper Data

In [ ]:
#Here A New Magic Cammand To Know The The Current Working File in Directory With All Innformation
!ls   -lh

total 4.0K
drwxr-xr-x 1 root root 4.0K Sep 26 13:45 sample_data


In [ ]:
#Here I Created Many Array
Array10=np.random.rand(1000,25)
Array11=np.random.rand(10770,65)
Array12=np.random.rand(1000,125)
Array13=np.random.rand(100,2500)

In [ ]:
np.savetxt("Example01.txt",Array10,delimiter=",")  

In [ ]:
np.save("Example02",Array10)     

In [ ]:
!ls   -lh 

total 812K
-rw-r--r-- 1 root root 611K Oct  2 06:15 Example01.txt
-rw-r--r-- 1 root root 196K Oct  2 06:15 Example02.npy
drwxr-xr-x 1 root root 4.0K Sep 26 13:45 sample_data


In [ ]:
np.savez("Example03",Array10,Array11,Array12,Array13)   

In [ ]:
!ls   -lh

total 9.2M
-rw-r--r-- 1 root root 611K Oct  2 06:15 Example01.txt
-rw-r--r-- 1 root root 196K Oct  2 06:15 Example02.npy
-rw-r--r-- 1 root root 8.4M Oct  2 06:15 Example03.npz
drwxr-xr-x 1 root root 4.0K Sep 26 13:45 sample_data


In [ ]:
Load01=np.load("Example03.npz")
print(Load01,type(Load01))

<numpy.lib.npyio.NpzFile object at 0x7fd20887ea90> <class 'numpy.lib.npyio.NpzFile'>


In [ ]:
Load01.files   

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [ ]:
Load01["arr_2"] 

array([[0.47087907, 0.20734134, 0.43377408, ..., 0.353902  , 0.34258929,
        0.32822943],
       [0.92792059, 0.71970029, 0.42311571, ..., 0.7399429 , 0.68286228,
        0.01677071],
       [0.09677263, 0.92737673, 0.58802892, ..., 0.16992323, 0.19645571,
        0.22083108],
       ...,
       [0.65361962, 0.95858922, 0.97629576, ..., 0.02765006, 0.07237242,
        0.6830766 ],
       [0.67773606, 0.26224241, 0.96137564, ..., 0.93021011, 0.63409519,
        0.97188548],
       [0.44369592, 0.37491774, 0.28626218, ..., 0.59362842, 0.53061547,
        0.04896073]])

In [ ]:
np.savez_compressed("Example03_Compressed",Array10,Array11,Array12,Array13)  

In [ ]:
ls -lh   

total 18M
-rw-r--r-- 1 root root 611K Oct  2 06:15 Example01.txt
-rw-r--r-- 1 root root 196K Oct  2 06:15 Example02.npy
-rw-r--r-- 1 root root 8.0M Oct  2 06:15 Example03_Compressed.npz
-rw-r--r-- 1 root root 8.4M Oct  2 06:15 Example03.npz
drwxr-xr-x 1 root root 4.0K Sep 26 13:45 sample_data/


Statistics Rules With Numpy

In [ ]:
Array14=np.random.rand(1412)  

Mean Of Array Is Subtracted The Array01 Has Zero Mean. i.e(xi - xbar)

In [ ]:
Array14Mean=np.mean(Array14)  

In [ ]:
Array1401=Array14-Array14Mean  

In [ ]:
np.mean(Array1401)            

-1.1353838863730354e-16

Computing Mean With Smaller Set Of Values

In [ ]:
for U in range (0,990):
    Array1401=Array14[0:U]
    K=(np.mean(Array14))
    print(U,K)

0 0.5030439078004971
1 0.5030439078004971
2 0.5030439078004971
3 0.5030439078004971
4 0.5030439078004971
5 0.5030439078004971
6 0.5030439078004971
7 0.5030439078004971
8 0.5030439078004971
9 0.5030439078004971
10 0.5030439078004971
11 0.5030439078004971
12 0.5030439078004971
13 0.5030439078004971
14 0.5030439078004971
15 0.5030439078004971
16 0.5030439078004971
17 0.5030439078004971
18 0.5030439078004971
19 0.5030439078004971
20 0.5030439078004971
21 0.5030439078004971
22 0.5030439078004971
23 0.5030439078004971
24 0.5030439078004971
25 0.5030439078004971
26 0.5030439078004971
27 0.5030439078004971
28 0.5030439078004971
29 0.5030439078004971
30 0.5030439078004971
31 0.5030439078004971
32 0.5030439078004971
33 0.5030439078004971
34 0.5030439078004971
35 0.5030439078004971
36 0.5030439078004971
37 0.5030439078004971
38 0.5030439078004971
39 0.5030439078004971
40 0.5030439078004971
41 0.5030439078004971
42 0.5030439078004971
43 0.5030439078004971
44 0.5030439078004971
45 0.503043907800497

In [ ]:
np.cumsum?

In [ ]:
np.cumsum(Array14)

array([4.00548695e-01, 5.81606819e-01, 1.06977941e+00, ...,
       7.09301013e+02, 7.09460666e+02, 7.10297998e+02])

Effect Of OutLiers on Mean And Median

In [ ]:
Array15=np.random.randint(1,200,100)  

In [ ]:
np.mean(Array15)    

109.91

In [ ]:
np.median(Array15)     

114.5

In [ ]:
Array1501=np.append(Array15,[1412,1214,22144])      

In [ ]:
np.mean(Array1501)   

347.19417475728153

In [ ]:
np.median(Array1501)       

118.0

In [ ]:
#Here We Can Conclude That Mean Is Outlier Senstive But Not Median

Effect Of Sacling And Shifting



In [ ]:
Array16=np.random.rand(14012)   

In [ ]:
np.mean(Array16)

0.5019127928534334

In [ ]:
np.median(Array16)

0.5054223748129314

In [ ]:
Array1601=60.584*Array16+1412  

In [ ]:
print(60.584*np.mean(Array16)+1412,np.mean(Array1601))  

1442.4078846422324 1442.4078846422324


In [ ]:
print(60.584*np.median(Array16)+1412,np.median(Array1601))   

1442.6205091556667 1442.6205091556667


Case Study

In [ ]:
!head Numpy-CaseStudy.tsv      

head: cannot open 'Numpy-CaseStudy.tsv' for reading: No such file or directory


**Questions **

1.   Find Mean,Median,IQR For All
2.   Find Histogram of ABC02 With 7 bins
3.   Find Mean Of ABC03 Group By 4
4.   Find Mean Of ABC01 When Its Is Low Than 141200
5.   Find Mean Of ABC02 When ABc03 Is Low Then 1214000
6.   Find The Mean For ABC01 Based on Which Quantile ABC03 Falls
7.   For Every Column Find Out Who has Scored More -ABC01 or ABC02
8.   How Many More Runs Does ABC01 On Average After Having Scored
9.   How Many Rows Did ABC01 Take To Score First 100 Scores,Next 100 Scores

In [ ]:
#Data01=np.loadtxt("https://raw.githubusercontent.com/UM1412/Data-Set/main/Numpy-CaseStudy.tsv")          

Above Cell Is Not Working Becasuse It Reads Only Float

In [ ]:
Data01=np.loadtxt("https://raw.githubusercontent.com/UM1412/Data-Set/main/Numpy-CaseStudy.tsv",skiprows=1)           #Here I Read The Tsv File Without st Row
Data01                           #Here I Printed The Data

array([[5.66540000e+04, 2.25200000e+03, 1.24286500e+06],
       [5.15500000e+03, 5.42000000e+02, 5.21564000e+05],
       [4.50000000e+01, 5.21500000e+03, 2.62900000e+03],
       [5.53215000e+05, 5.25150000e+04, 4.52858000e+05],
       [2.15400000e+03, 2.16580000e+04, 4.52124511e+08],
       [2.10542000e+06, 2.15240000e+04, 4.85215475e+08],
       [5.20550000e+04, 2.05000000e+02, 5.46135542e+10],
       [4.55208460e+07, 1.50000000e+01, 8.45215425e+09],
       [2.16545020e+00, 2.18522300e+04, 4.02455258e+11],
       [5.60140000e+04, 2.12600000e+03, 4.65214365e+08],
       [1.68500000e+03, 2.15515000e+05, 6.84351580e+07],
       [2.51531500e+06, 5.21584800e+06, 4.52550000e+04],
       [2.05524682e+09, 2.12155251e+08, 4.52155720e+07],
       [2.15150000e+04, 5.15215485e+09, 6.35487870e+07],
       [1.50000000e+02, 2.12412518e+09, 8.75463200e+06],
       [2.12500000e+03, 2.15158415e+09, 6.58315424e+09]])

In [ ]:
Data01.shape           

(16, 3)

In [ ]:
ABC01=Data01[:,0]               
ABC02=Data01[:,1]                
ABC03=Data01[:,2]                

In [ ]:
ABC03

array([1.24286500e+06, 5.21564000e+05, 2.62900000e+03, 4.52858000e+05,
       4.52124511e+08, 4.85215475e+08, 5.46135542e+10, 8.45215425e+09,
       4.02455258e+11, 4.65214365e+08, 6.84351580e+07, 4.52550000e+04,
       4.52155720e+07, 6.35487870e+07, 8.75463200e+06, 6.58315424e+09])

Problem 01

In [ ]:
#With Itreative Way
def Stats(ABC):                          
    print("Mean Is",np.mean(ABC))       
    print("Median",np.median(ABC))       #
    print("Inter Qurtile range",np.percentile(ABC,75)-np.percentile(ABC,25))        

In [ ]:
Stats(ABC01)                             
Stats(ABC02)                              
Stats(ABC03)                             

Mean Is 131633698.26034063
Median 36785.0
Inter Qurtile range 939251.25
Mean Is 602848669.139375
Median 21755.114999999998
Inter Qurtile range 56948478.25
Mean Is 29605930885.3125
Median 65991972.5
Inter Qurtile range 2008637627.75


Problem 02

In [ ]:
np.histogram(ABC02,bins=7)           

(array([13,  0,  2,  0,  0,  0,  1]),
 array([1.50000000e+01, 7.36022135e+08, 1.47204425e+09, 2.20806637e+09,
        2.94408849e+09, 3.68011061e+09, 4.41613273e+09, 5.15215485e+09]))

Problem03

In [ ]:
ABC03.shape              

(16,)

In [ ]:
ABC03By4=ABC03.reshape(4,4)        

In [ ]:
np.mean(ABC03By4,axis=1)            

array([5.54979000e+05, 1.60007621e+10, 1.00747238e+11, 1.67516831e+09])

Problem 04

In [ ]:
ABC0101=ABC01[ABC01>141200]         

In [ ]:
np.mean(ABC0101)         

421188323.6

Problem 05

In [ ]:
ABC0102=ABC01[ABC02>121400]         
np.mean(ABC0102)         

342964602.0

In [ ]:
print ("The End  \n Thank You")

The End  
 Thank You
